<?php
$static_url = Globals::getStaticUrl();
$base_url = Globals::getBaseUrl();
$version = Globals::getVersion();
$_general = Business_Addon_General::getInstance();

?>
</div>
<footer class="mt-5">
    <div class="main pt-0 pt-lg-5 mt-2">
        <div class="container container-home">

            <div class="footer-top">
                <div class="footer-top_logo">
                    <img src="/v2/images/logo-05.svg" width="318" height="132" class="auto-size" loading="lazy">
                </div>
                <p class="mb-1 footer-top_address">
                    <a href="https://maps.google.com/?q=85+W+Broadway,+New+York,+NY+10007,+USA&amp;ftid=0x89c25a1f26a2f7a1:0xa61f2f68453d917c" target="_blank">14B Đống Đa, Phường 3, Đà Lạt, Vietnam</a>
                </p>
                <div class="footer-top_contact mb-2">
                    <a href="tel:1900299222">1900 299 222</a>
                    <span class="pipe">|</span>
                    <a href="mailto:reservations@newcenturyhotel.vn">reservations@newcenturyhotel.vn</a>
                </div>
                <div class="footer-top_social">
                    <div class="footer-top_social_item">
                        <a href="https://www.facebook.com/newcenturyhotel.vn"><img src="/v2/images/icon-social/icon-facebook.svg" width="24" height="24" loading="lazy"></a>
                        <p class="footer-social_title">Facebook</p>
                    </div>
                    <div class="footer-top_social_item">
                        <a href=""><img src="/v2/images/icon-social/icon-instagram.svg" width="24" height="24" loading="lazy"></a>
                        <p class="footer-social_title">Instagram</p>
                    </div>
                    <div class="footer-top_social_item">
                        <a href=""><img src="/v2/images/icon-social/icon-location.svg" width="24" height="24" loading="lazy"></a>
                        <p class="footer-social_title">Address</p>
                    </div>
                    <div class="footer-top_social_item">
                        <a href=""><img src="/v2/images/icon-social/icon-phone.svg" width="24" height="24" loading="lazy"></a>
                        <p class="footer-social_title">Phone</p>
                    </div>
                    <div class="footer-top_social_item">
                        <a href=""><img src="/v2/images/icon-social/icon-twitter.svg" width="24" height="24" loading="lazy"></a>
                        <p class="footer-social_title">Twitter</p>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <p class="copyrights">© 2023 New Century</p>
            </div>
        </div>
    </div>
</footer>

<?php echo $this->inlineScript(); ?>

<!--<script src="v2/js/jquery-3.3.1.slim.min.js" type="text/javascript" ></script>-->
<!--<script src="v2/vendor/slick/slick.min.js" type="text/javascript"></script>-->
<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>-->

<!--<script src="v2/vendor/swiper/swiper-bundle.min.js" type="text/javascript"></script>-->
<!--<script src="v2/js/script.js" type="text/javascript"></script>-->
<!--<script src="v2/js/home.js" type="text/javascript"></script>-->
</body>
</html>
