<style>

    .ic {
        display: inline-flex;
        align-self: center;
        width: 16px;
        height: 16px;
        margin: 0 6px 0 0;
        background-position: center center;
        background-size: contain;
        background-repeat: no-repeat;
        cursor: pointer;
    }
    .loading-content {
        position: fixed;
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        background: rgba(240, 240, 240, 0.4);
        z-index: 99999;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-align: center;
        align-items: center;
        -ms-flex-pack: center;
        justify-content: center;
    }
    .ic.ic-loading {
        background-image: url(https://stcv4.hnammobile.com/v7/images/icon/loading.svg?v=5638);
    }
    .loading-content i {
        width: 50px;
        height: 50px;
        color: #ff5400;
        animation-duration: 2s;
        animation-iteration-count: infinite;
        animation-name: loading-ajax-content;
    }

    .hide {
        display: none;
    }
    @keyframes loading-ajax-content {
        0%   {transform: rotateZ(0deg);}
        100% {transform: rotateZ(360deg);}
    }
</style>