<style>
    .event-data-link-remove{
        width: 70px;
    }
    .row.group-data-item {
        margin: 10px;
        border: 1px solid #ccc;
        padding: 10px 5px;
    }
</style>
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Thêm chương trình Loyalty</h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <form onsubmit="submitPromotion(this)">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Thông tin chung</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Tên chương trình</label>
                                <input type="text" name="title" id="inputName" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="type">Loại chương trình</label>
                                <select onchange="changeTypePromotion(this)" name="type" id="type" class="form-control select2" style="width: 100%;" >
                                    <option selected="" value="0">Chọn loại chương trình</option>
                                    <option value="1">Tích điểm sinh nhật</option>
                                    <option value="2">Ngày đặc biệt</option>
                                    <option value="3">H.DAY</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="memberships">Hạng thành viên</label>
                                <select name="memberships" id="memberships" class="form-control select2" style="width: 100%;" >
                                    <option selected="" value="0">Chọn hạng thành viên</option>
                                    <option value="1">H.MEMBER</option>
                                    <option value="2">H.GOLD</option>
                                    <option value="3">H.VIP</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Thời gian bắt đầu</label>
                                <div class="input-group date" id="reservationdatetimestart" data-target-input="nearest">
                                    <input type="text" name="dateStart" class="form-control datetimepicker-input" data-target="#reservationdatetimestart"/>
                                    <div class="input-group-append" data-target="#reservationdatetimestart" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Thời gian kết thúc</label>
                                <div class="input-group date" id="reservationdatetimeend" data-target-input="nearest">
                                    <input type="text" name="dateEnd" class="form-control datetimepicker-input" data-target="#reservationdatetimeend"/>
                                    <div class="input-group-append" data-target="#reservationdatetimeend" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="inputPoint">Điểm cộng thêm (Tính theo %)</label>
                                <input type="number" name="point" id="inputPoint" placeholder="20" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="inputStatus">Trạng thái</label>
                                <div class="">
                                    <input type="checkbox" name="status" value="1" checked data-bootstrap-switch>
                                </div>

                            </div>

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <div class="col-md-6">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Thông tin chuong trình</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body" id="detail-promotion">

                        </div>
                        <div class="card-footer" id="detail-promotion-add">

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="https://www.hnammobile.com/admin/ajax/list-products" class="btn btn-secondary">Hủy</a>
                    <input type="submit" value="Tạo sản phẩm khuyến mãi" class="btn-add btn btn-success float-right">
                </div>
            </div>
        </form>

    </div><!-- /.container-fluid -->
</section>
