<style>
    .input-group-lg>.custom-select, .input-group-lg>.form-control:not(textarea) {
        font-size: 16px;
        height: calc(2.3rem + 2px);
    }
    .input-group-lg>.input-group-append>.btn{
        padding: 5px 10px;
        font-size: 17px;
        line-height: 1.5;
        border-radius: 0.3rem;
    }
</style>
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1 class="m-0">Top 3 item id được click nhiều nhất tại Url:</h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
            <div class="row">
                <div class="col-md-10 offset-md-1">
                    <div class="row">
                    <?php
                        if(isset($_POST['url'])) {
                            // Giải mã giá trị id từ input ẩn
                            $originalUrlEncoded = $_POST['url'];
                            $originalUrlDecoded = urldecode($originalUrlEncoded);
                        
                            // Lấy ra giá trị id đã giải mã
                            $url = $originalUrlDecoded;
                            $getTop3Itemid = Business_Addon_Hnproducts::getInstance()->getTopItemidClickPerBlogUrl($url);
                        }
                    ?>
                    </div>

                </div>
            </div>


        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <table id="tableCate" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>TOP</th>
                                <th>ID sản phẩm</th>
                                <th>Số lượt click</th>
                            </tr>
                            </thead>
                            <tbody>
                                <?php if ($getTop3Itemid): $key=0;?>
                                    
                                    <?php foreach ($getTop3Itemid as $item): ?>
                                        <tr>
                                            <td><?php echo ++$key; ?></td>
                                            <td><?php echo $item['itemid'] ?></td>
                                            <td><?php echo $item['frequency'] ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                <tr><td colspan="3"></td></tr>
                                <?php endif; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>TOP</th>
                                <th>ID sản phẩm</th>
                                <th>Số lượt click</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    </div><!-- /.container-fluid -->
</section>