<style>
    .input-group-lg>.custom-select, .input-group-lg>.form-control:not(textarea) {
        font-size: 16px;
        height: calc(2.3rem + 2px);
    }
    .input-group-lg>.input-group-append>.btn{
        padding: 5px 10px;
        font-size: 17px;
        line-height: 1.5;
        border-radius: 0.3rem;
    }
</style>
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1 class="m-0">Top User ID có nhiều transaction:</h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
            <div class="row">
                <div class="col-md-10 offset-md-1">
                    <div class="row">
                    
                    </div>

                </div>
            </div>


        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <table id="tableCate" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>TOP</th>
                                <th>UID</th>
                                <th>Số lượt transaction</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if ($this->listCate): $key=0;?>
                                    
                                    <?php foreach ($this->listCate as $item): ?>
                                        <tr>
                                            <td><?php echo ++$key; ?></td>
                                            <form id="form<?php echo $key; ?>" action="/admin/home/blogurlperuid" method="post">
                                                <!-- Input ẩn chứa giá trị url -->
                                                <input type="hidden" name="uid" value="<?php echo $item['uid']; ?>">
                                            </form>
                                            <td>
                                                <!-- Sử dụng JavaScript để gửi form khi người dùng nhấn vào đường link -->
                                                <a href="#" onclick="document.getElementById('form<?php echo $key; ?>').submit(); return false;">
                                                    <?php echo $item['uid']; ?>
                                                </a>
                                            </td>

                                            <!-- <td><?php echo $item['uid'] ?></td> -->
                                            <td><?php echo $item['clicksCount'] ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                <tr><td colspan="3"></td></tr>
                                <?php endif; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>TOP</th>
                                <th>UID</th>
                                <th>Số lượt transaction</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    </div><!-- /.container-fluid -->
</section>